apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-prodcution-e2e-pipeline-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: complete-prodcution-e2e-pipeline
  template:
    metadata:
      labels:
        app: complete-prodcution-e2e-pipeline
    spec:
      containers:
        - name: register-app
          image: kaoutar-LM/complete-prodcution-e2e-pipeline-pipeline:1.0.0-9
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
